name: Check Tasks

permissions: read-all

on: pull_request

jobs:
  check-tasks:
    # yamllint disable-line rule:line-length
    uses: outoforbitdev/reusable-workflows-library/.github/workflows/check-tasks.yml@main
